package com.mobdeve.s12.group8.glimpse

class PostsList {
    val postList = listOf(
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
        R.drawable.post1,
        R.drawable.post2,
        R.drawable.post3,
        R.drawable.user1,
        R.drawable.user2,
        R.drawable.user3,
    ) // This is a List of Ints
}
